# Generated by Django 2.1.8 on 2019-05-06 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_styledlink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styledlink',
            name='int_destination_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ['Page', 'Post']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
